version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: d@tabase
      MYSQL_DATABASE: Books
      MYSQL_USER: root
      MYSQL_PASSWORD: d@tabase
    ports:
      - "3305:3306"
